language: node_js
node_js:
  - "6"
  - "5"
  - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
      repo_token: 7e9342659cccc97e7107c9d07df0026e9e4e8382a55ade170045ca6fe22a1c3b
before_script:
  - npm i -g mocha
  - npm i -g istanbul
after_script:
  - npm i -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
